name: dart_deepseek
description: A Dart SDK for DeepSeek AI API with streaming support and chain of thought.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  json_annotation: ^4.9.0
  stream_transform: ^2.1.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
